version: '3.7'
services:
  mysql_standalone:
    build:
      context: ./mysql-docker
      dockerfile: Dockerfile
    container_name: mysql_standalone
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: developers
    ports:
      - 3307:3306