version: '3.7'
services:
  mysql_standalone:
    image: mysql:8.0.20
    container_name: mysql_standalone
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
    ports:
      - 3307:3306